### ISSUE TITLE
Definir flow de autenticação

### ISSUE THREAD

**Issue by ruymon** [ruymon/calypso#31]

**Comment by ruymon** [comment]
@fonfs @lcnssantos  

Podemos modificar para a autenticação ser somente Google? Sendo assim, retirando o email e senha..

**Comment by fonfs** [comment]
> [@fonfs](https://github.com/fonfs) [@lcnssantos](https://github.com/lcnssantos)
> 
> Podemos modificar para a autenticação ser somente Google? Sendo assim, retirando o email e senha..

Não. Não faz sentido forçar o usuário a ter uma conta Google para usar o sistema.

Não sei o nível de complexidade da tarefa, mas sugiro variar o máximo possível a possibilidade de usar OAuth, a partir, inclusive, das contas vinculadas ao Skyscope. Pode ser preferível aos membros de uma rede logar pelo OAuth da rede, apontando para a conta vinculada. Pode ser interessante logar usando sua conta do Google, Facebook, X, ou até Navigraph etc.

Mas, mesmo assim, é absolutamente necessária a possibilidade ter uma conta para logar via e-mail e senha, para qualquer usuário que, hipoteticamente, não tenha vinculação com uma rede de simulação ou rede social.

@ruymon: para MVP, considerar login via e-mail e senha, via VATSIM, via IVAO e via Google, o que já deve abarcar a maior quantidade de usuários.
