### ISSUE TITLE
Exibir perfil vertical

### ISSUE THREAD

**Issue by ruymon** [ruymon/calypso#36]
Na tela de detalhes do voo exbir o perfil vertical do voo.

Inspiração

![Image](https://github.com/skyscope-app/skyscope-web/assets/50504050/698071a4-0b72-4e2f-95e2-52809797162c)

**Comment by ruymon** [comment]
@fonfs  Essa feature ainda faz sentido? Talvez ser exibida na tela de detalhes de um voo.

**Comment by fonfs** [comment]
> [@fonfs](https://github.com/fonfs) Essa feature ainda faz sentido? Talvez ser exibida na tela de detalhes de um voo.

Acho interessante, mas num release posterior.
