### ISSUE TITLE
Salvar e sincronizar configurações de exibição

### ISSUE THREAD

**Issue by ruymon** [ruymon/calypso#41]
## Comportamento padrão:

- Se for a primeira vez do usuário no sistema, popular armazenamento com configurações padrão.
- Ao mudar as opções de exibição, atualizar no armazenamento também

### Configurações padrão:

```typescript
interface MapSettings {
	mapStyle: 'dark' | 'light' | 'satellite'
	hideMapLabels: boolean
	initialPosition: {
		lat: number
		lng: number
		zoom: number // Zoom level should be nested in the maxZoom and minZoom interval
	}
	layers: {
		vatsim: {
			isVisible: boolean
			iconColor: string // hex color
		}
		ivao: {
			isVisible: boolean
			iconColor: string // hex color
		}
	}
}
```

**Comment by fonfs** [comment]
@ruymon: isso afeta muito o UX. Viabilizar isso tão prioritariamente quanto possível.

**Comment by ruymon** [comment]
Esperando o https://github.com/skyscope-app/skyscope-backend/issues/66

**Comment by fonfs** [comment]
@ruymon 
Isso impacta fortemente o UX. Considere priorizar.

**Comment by ruymon** [comment]
@fonfs Ciente
