### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by ruymon** [ruymon/calypso#44]
## Requisitos:

- [x] Hierarquia de Títulos
- [x] âncoras
- [x] Gerar link com id da seção atual
- [x] listas
- [x] tabelas
- [x] blocos de código
- [x] vídeos / imagens
- [x] códigos em linha
- [x] Códigos de atenção
- [x] Separadores

**Comment by fonfs** [comment]
Acho relevante pra anunciarmos projetos de novas features, podendo até ser usado como divulgador pros sites de notícias de simulação, como FSElite. O formato do blog da Vatsim Tech (https://tech.vatsim.net) é muito bom e parece ser simples. Algo apenas usando Markdown já seria suficiente.

**Comment by ruymon** [comment]
https://github.com/skyscope-app/skyscope-web/pull/47
