### ISSUE TITLE
Refatorar detalhes do voo

### ISSUE THREAD

**Issue by fonfs** [ruymon/calypso#46]
Melhorar a página de detalhes do voo.

Para agradar simplistas e técnicos, sugiro duas apresentações, divididas por aba: uma mais mastigada, como está feita atualmente, e uma mais técnica, no padrão do formulário de PV da ICAO.

Para a apresentação mais simples, alterar as seguintes informações:

- [x] **IVAO**: incluir a VID no local de "Unknown Pilot"

![Image](https://github.com/skyscope-app/skyscope-web/assets/1394072/729b272e-7593-4fa9-be1b-fe5c59aaf54b)

- [x] **Ambos**: substituir as legendas para ALT, GS, HDG e XPDR (não é necessário traduzir).

![Image](https://github.com/skyscope-app/skyscope-web/assets/1394072/7d8fe5b0-3c4c-4b35-b49b-72834b1cb6bc)

- [x] **Ambos**: mudar o título para **Rota** e o subtítulo para **Informações sobre a rota da aeronave**. Nada é tratado aqui da localização atual da aeronave, mas sim da origem e destino do plano de voo.

![Image](https://github.com/skyscope-app/skyscope-web/assets/1394072/03e96dd3-7327-4977-b600-5dca55ef8f90)

- [x] A bem da simplicidade (isto é, para diminuir o tamanho vertical da aba), sugiro botar origem e destino lado a lado, tal como os alternativos. _Avaliar também a possibilidade de suprimir a informação do ALTN2 dos voos da Vatsim, já que nunca serão utilizados_.

![Image](https://github.com/skyscope-app/skyscope-web/assets/1394072/00db4d91-f4ac-40d9-9923-0b27751f1cc2)

- [x] **Avaliar**: O que seria o estado atual da aeronave?

![Image](https://github.com/skyscope-app/skyscope-web/assets/1394072/a8a667c3-7019-4c18-b942-49ced8a7e9d9)

- [x] Juntar a informação do transponder no equipamento **(<EQPT>/<TRANSP>)** (ex.: SDGRY/SB1)
- [x] Juntar a esteira de turbulência para o tipo da aeronave **(<TYP>/<CAT>)** (ex.: A320/M)

![Image](https://github.com/skyscope-app/skyscope-web/assets/1394072/439cd595-50be-4c32-bca1-b8dac4d6af40)

- [x] Enquanto não tiver o que mostrar, remova a info do _Empty State_.

![Image](https://github.com/skyscope-app/skyscope-web/assets/1394072/8bfe7dc9-a636-4cd6-a252-706a2dd5ccac)

- [x] Incluir a unidade de medida de velocidade (opção 1: incluir o tipo, padrão ICAO; opção 2: inserir depois [448 **nós**]).
- [x] A informação apresentada pra altitude não é FL. Apresentar, ou um (FL370), ou outro (37000 pés).
- [x] Incluir o RMK, formato raw.

![Image](https://github.com/skyscope-app/skyscope-web/assets/1394072/3b2fc2e7-1802-4231-9860-e79c9e021896)

-------

Adicionalmente, criar uma aba onde as informações vão para o padrão do formulário ICAO, como você fez na época.

**Comment by ruymon** [comment]
## Outras melhorias

- [ ] Track do voo verdadeira com gradiente de altura
- [ ] Track do voo prevista (Navigraph waypoints)
- [ ] Clicar fora da página ou modo deixar fixado
- [ ] Modo tela cheia (url params no layout do app).
