### ISSUE TITLE
Camadas Meteorológicas

### ISSUE THREAD

**Issue by fonfs** [ruymon/calypso#50]
@ruymon avaliar o uso da seguinte API pra termos mais camadas meteorológicas: https://app.tomorrow.io

**Comment by ruymon** [comment]
Bloqueado pois não entendi uma desgraça da Issue @fonfs

**Comment by ruymon** [comment]
@fonfs Falta detalhamento.

**Comment by ruymon** [comment]
@fonfs Vamos reverter para o simples Rain Viewer como na versão inicial, visando agilidade para lançar?

**Comment by fonfs** [comment]
@ruymon vamos.

**Comment by ruymon** [comment]
@fonfs Em andamento
