### ISSUE TITLE
Colocar Google Analytics

### ISSUE THREAD

**Issue by ruymon** [ruymon/calypso#72]

**Comment by ruymon** [comment]
Aguardando permissões. @lcnssantos

**Comment by ruymon** [comment]
Liberado novamente.

**Comment by fonfs** [comment]
@ruymon @lcnssantos 
Não tenho competência pra julgar a relevância disso. Se for importante para o produto inicial, o que falta?

**Comment by ruymon** [comment]
@fonfs Em tese é algo muito rápido de implementar no código. O  grande problema é configurar no Dashboard do Google os dados e os KPIs. Sendo sincero, de todos nós, você (@fonfs) seja o mais capacitado para desbravar o painel de estatísticas.

**Comment by fonfs** [comment]
@ruymon estatística só faz sentido quando você sabe o que quer analisar. O que se quer analisar?

**Comment by ruymon** [comment]
@fonfs Todos os tipos de dados que podem nos ajudar a guiar o desenvolvimento. Exemplo: Se temos, de forma quantitativa, que  os usuários não usam o Skyscope em telas menores de X, não vamos gastar tempo com responsividade. 

Principais coisas que acho importante analisar
- País dos usuários 
- Navegador
- Sistema operacional
- Horários de pico
-Páginas mais acessadas
- Tema mais usado

Exemplos... Da para coletar MUITA COISA.

**Comment by fonfs** [comment]
@ruymon então eu posso ver, mas primeiro eu preciso saber o que vocês querem saber antes de criar algo.

**Comment by ruymon** [comment]
@fonfs Logo mais vou liberar o painel para ti. Tu vai ver que logo de cara vem muito dado, compete ao gestor do dashboard organizar. Acerca do conteúdo, deixo ao seu critério uma vez que está gerindo as prioridades. O painel do analytics não compreende dados técnicos, ou seja, nós programadores usamos outro painel.
