### ISSUE TITLE
Leiaute para Dispositivos Móveis

### ISSUE THREAD

**Issue by ruymon** [ruymon/calypso#8]
- [ ] Map view for mobile

**Comment by fonfs** [comment]
@ruymon não entendo que seja algo de máxima relevância para o MVP, haja vista o fato dos outros produtos concorrentes não terem suporte completo pra mobile e isso não ser uma questão de máxima importância.

Prepare apenas o suporte mínimo necessário, mas não perca muito tempo com isso. Posteriormente, podemos retornar nessa tarefa e vendê-la como uma atualização relevante pra saúde do produto.

**Comment by ruymon** [comment]
@fonfs Atualmente a página principal já está amigável para dispositivos móveis. Já o app precisa ser completamente refatorado para dispositivos móveis já que grande parte dos itens estão "flutuando em cima do mapa".

**Comment by fonfs** [comment]
@ruymon dê apenas suporte básico ao app. Adições e melhoramentos podem ser realizados em um futuro oportuno.

**Comment by ruymon** [comment]
Roger.
