### ISSUE TITLE
Simbrief API Integration

### ISSUE THREAD

**Issue by ruymon** [ruymon/calypso#9]
- [ ] Fetch Navlog object to show predicted route

**Comment by ruymon** [comment]
https://www.simbrief.com/api/xml.fetcher.php?userid=72475&json=1

**Comment by fonfs** [comment]
@ruymon com o retorno da Navigraph, avaliar a implementação dessa feature para o lançamento do produto, bem como a complexidade.

**Comment by ruymon** [comment]
@fonfs Apesar do OK da Navigraph, os nossos Suecos ainda não providenciaram nossa chave. Sendo assim, não descartei tal possibilidade de integração. Para além, podemos ponderar na situação de ambas trabalharem em conjunto. 
- Navigraph como provedor de dados navegacionais
- Simbrief = Extrair dados do plano de voo atual ou importar histórico de voos para gerar um Flight book
