### ISSUE TITLE
[BUG] Atraso ao clicar em elementos do mapa

### ISSUE THREAD

**Issue by ruymon** [ruymon/calypso#97]
Auto explicativo.

**Comment by ruymon** [comment]
@fonfs Você já tinha comentado sobre isso. Agora, outros usuários também relataram o mesmo problema.

**Comment by fonfs** [comment]
@ruymon isso tem impactado negativamente o uso da ferramenta. Como não dá pra diminuir o tempo de carregamento dos dados, ludibriar o usuário é a solução mais adequada pra mim.

**Comment by ruymon** [comment]
@fonfs Estou investigando agora. O curioso, o atraso não é da página. É como se o mapa não falasse para o navegador abrir. No memento que o evento é de fato disparado, o carregamento entra em ação como esperado.

**Comment by ruymon** [comment]
Curioso. KKKK
